### ISSUE TITLE
Is it possible to change the way the app names the branches

### ISSUE THREAD

**Issue by carlhua** [osowskit/atlassian-github-app-addon#37]
can we configure on how the branches are named?

**Comment by osowskit** [comment]
Thanks for your interest in this plugin. This has been discussed in https://github.com/osowskit/atlassian-github-app-addon/issues/20#issuecomment-395516297. I'm not expecting to add this in the near term but would appreciate hearing how you would like to name the branches

**Comment by carlhua** [comment]
Use the title of the jira ticket 

Currently it’s not useable because if it just said JIRA-1 - it cannot be used with open source software if jira is closed off to the public.

**Comment by fabich** [comment]
@osowskit any updates on this?

**Comment by antonio-santos** [comment]
Hey @osowskit 

Thanks for you plugin. We are using this to create automatically the branches from JIRA. But we are using GitFlow in our branches organization. We need to have a way of configuring the branch name to have feature/<JIRA-issue> and it also has to be created from the develop branch instead of the master.

Do you think this feature is possible? Do you accept a PR?

Thanks

**Comment by osowskit** [comment]
> Do you think this feature is possible? Do you accept a PR?

Yes. This feature is possible. It could be modified to pull these settings from a file stored in the repository ([example](https://probot.github.io/apps/stale/#installation)). 

I don't have plans to add this but would welcome PRs. There is a larger refactor I can push to this repo so let me know if you plan on working on this.

**Comment by eddyaman** [comment]
We are keen to see this request come to life. +1

**Comment by eddyaman** [comment]
You know what? Instead of making the branch name customisable, we can just add `jira-issue-type` in front of the `jira-key` in the branch name.
So the end result would be `repo-name/issue-type/jira-issue-key`

**Comment by osowskit** [comment]
👋I'm willing (and previously have offered) to help developers fork this repository and add this feature; I can provide a portion of the code to get the settings file from a Repository. I was intending on keeping the add on free and avoid actively developing features - i.e. it's in maintenance mode.

However, I will consider implementing this if the users are willing to help cover the cost of implementing this feature : https://www.gofundme.com/customized-branch-naming. I apologize if this seems tacky but hope you understand there's a cost to this request. 🙏

**Comment by socialreport** [comment]
Not sure this is going to work for us.  It doesn't create branches like the Bitbucket plugin does; `task/app-123-task-title`.  Instead it creates an `app-123` branch.

**Comment by osowskit** [comment]
> Use the title of the jira ticket

This plugin was architected to avoid modifying/accessing Jira tickets directly which this request requires. This improved security for users and enables this to execute at scale. Adding this is nontrivial and relies on caching branch names.

> Instead of making the branch name customisable, we can just add jira-issue-type in front of the jira-key in the branch name. So the end result would be repo-name/issue-type/jira-issue-key

Atlassian's [context parameters](https://developer.atlassian.com/cloud/jira/platform/context-parameters/#jira-context-parameters-) do not provide enough information to access this information for, `issue-type`, without a large redesign of this plugin and larger risk exposure. The `issue-type` can be configured by each jira instance - hence my project's **Bug** as `10104` won't likely match up to another Jira project's **Bug**.

Because I'm offering this plugin for free, I cannot justify time to make this larger refactor. I would consider developing a separate, paid plugin that could provide this. Let me know if you'd be willing to pay ~$3/user/month for a version that supports customizing branch names -- either `issue_type/issue_key` or `issue_title`.

> Thanks for you plugin. We are using this to create automatically the branches from JIRA. But we are using GitFlow in our branches organization. We need to have a way of configuring the branch name to have feature/ and it also has to be created from the develop branch instead of the master.

@antonio-santos this is something that should be straightforward to provide. Can you confirm that every branch you want created would be `feature/SENG-1234` off of `develop`?

**Comment by osowskit** [comment]
@antonio-santos i've added the ability to use the branch naming as you've requested. You will need to add a file `.github/jira-bot.yaml` on the `master` (or GitHub's default branch) with the contents 

```
branch_pattern: 1
```

**Comment by osowskit** [comment]
I've added the ability to manually enter the branch name through the UI. Note that though these will always have the Jira key as the prefix, e.g. `SENG-1234/my-fav-branch`. 

1. You will need to add a file `.github/jira-bot.yaml` on the **master** (or GitHub's default branch) for every repository you'd like to create custom branch names. 
2. After adding this file, you will need to use the **Select Repos** feature to Remove and Add this Repository.

This file should have:
```
branch_pattern: 2
```
[example](https://github.com/osowskit/an-repo/blob/master/.github/jira-bot.yaml)

**Comment by KeentGG** [comment]
> I've added the ability to manually enter the branch name through the UI. Note that though these will always have the Jira key as the prefix, e.g. `SENG-1234/my-fav-branch`.
> 
> 1. You will need to add a file `.github/jira-bot.yaml` on the **master** (or GitHub's default branch) for every repository you'd like to create custom branch names.
> 2. After adding this file, you will need to use the **Select Repos** feature to Remove and Add this Repository.
> 
> This file should have:
> 
> ```
> branch_pattern: 2
> ```
> 
> [example](https://github.com/osowskit/an-repo/blob/master/.github/jira-bot.yaml)

what does the value of the branch pattern refers to? what's the difference between
`branch_pattern: 1` and `branch_pattern: 2`?

**Comment by osowskit** [comment]
There is more in the [readme](https://github.com/osowskit/atlassian-github-app-addon#custom-branch-names). 

In short, 1 represents a GitFlow pattern (branch off of develop) and 2 allows setting a custom branch name. If you have any additional questions or requirements, you can join the slack channel and can provide more information there.
